### PR TITLE
fix Evaluation Error on require of puppet/util/rundeck_acl

### PR DESCRIPTION
**Pull request by Tombar**
Just the @ak0ska suggestion from @JesperTerkelsen fork on issue #125

### CODE REVIEW

**Comment by JesperTerkelsen** [comment]
:+1:

**Comment by jyaworski** [comment]
Please rebase against the current master; a lot has changed. This PR is still valid against it, though.

**Comment by JesperTerkelsen** [comment]
I made a PR on latest master: https://github.com/puppet-community/puppet-rundeck/pull/142

**Comment by liamjbennett** [comment]
Closing in favour of #142

**Pull request closed without merging**
