### PR TITLE
adding usage section with shared ldap configuration example

### PR DESCRIPTION
**Pull request by rooty0**

### CODE REVIEW

**Comment by liamjbennett** [comment]
Can I suggest putting that code into another file e.g. examples/ldap_shared.pp and then linking to that from the usage section in the README?

**Comment by rooty0** [comment]
@liamjbennett, sounds reasonable, fixing

**Comment by rooty0** [comment]
houston we have a problem
actually "true" and "false " should be as a string

**Comment by rooty0** [comment]
@liamjbennett done

**Comment by nibalizer** [comment]
Thanks!

**Pull request merged**
