### PR TITLE
Fixing the autoload of the rundeck_acl function.

### PR DESCRIPTION
**Pull request by liamjbennett**
There was an issue with autoloading the function when it was in
lib/puppet/util so I have refactored it to move it into a more
appropriate location under the PuppetX module namespace.

### CODE REVIEW

**Comment by jyaworski** [comment]
@liamjbennett I think this is a concern for @igalic and https://github.com/puppet-community/modulesync_config/issues/14

It's not useful to cry about comments.

**Comment by jyaworski** [comment]
I also just ran into this, personally. Puppetserver 2, latest puppet4 agent. This doesn't seem to fix it, at least for me.

http://pastebin.com/index/NkibipFS

**Comment by liamjbennett** [comment]
I am not sure why you are getting that error if you are using this PR as there is no reference to puppet/util/rundeck_acl any more.

**Comment by jyaworski** [comment]
I'm not entirely sure, but #147 fixed it for me.

**Comment by liamjbennett** [comment]
Ok I definitely need to write some acceptence tests to validate this change.

**Comment by jyaworski** [comment]
If you do continue this PR, there's precedent to use the puppet_x namespace rather than puppetx. I believe inifile uses it.

**Comment by igalic** [comment]
@jyaworski puppet_x / puppetx is a pattern. many people use their own (company's name as) namespace.

**Comment by liamjbennett** [comment]
Is there a preference over which one puppetx vs puppet_x ??

**Comment by jyaworski** [comment]
I suppose it doesn't really matter. We could even do something like puppet/rundeck.

**Comment by igalic** [comment]
@liamjbennett / @jyaworski are we ready to try this again?

**Comment by jyaworski** [comment]
@igalic right.

@liamjbennett see https://github.com/puppet-community/puppet-mcollective/blob/master/.sync.yml#L4

**Comment by chad-upton** [comment]
Still getting this autoloading issue:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/parser/functions/validate_rd_policy: cannot load such file -- puppetx/rundeck/acl on node rundeck
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by chad-upton** [comment]
And somehow it was fixed by running a puppet check in on the puppet master.

**Pull request merged**
