### PR TITLE
Validate ACLs against rd-acl recommendations

### PR DESCRIPTION
**Pull request by jyaworski**
Validates against RD 2.6's rd-acl validate.

@liamjbennett

### CODE REVIEW

**Comment by igalic** [comment]
@jyaworski can you briefly explain what this code does?
perhaps amend the commit message too ;)

**Comment by jyaworski** [comment]
@igalic done.

So Rundeck 2.6 introduced 'rd-acl validate' to lint and validate aclpolicy files. This changes the template to conform to those linting recommendations.

What this does, essentially, is adds a hyphen only to every other block (a rule is considered an action and allow/deny statement).

**Comment by jyaworski** [comment]
I'll admit that this isn't a good solution, as every-other line is only the most common way of specifying ACLs. A better way would have the ACLs grouped in a hash somehow, but that's a breaking change.

**Comment by jyaworski** [comment]
Hold off on merging this. I'm going to refactor it.

**Comment by jyaworski** [comment]
OK, now it's good to merge. I was overthinking it in my last few comments. It was already an array of hashes; no compatibility break.

**Comment by igalic** [comment]
@jyaworski can we introduce a test for this?

**Comment by jyaworski** [comment]
@igalic the validate_acl function is kind of like a test for this already. Were you meaning something else?

**Comment by igalic** [comment]
what i meant is actual spec tests, such as https://github.com/puppet-community/puppet-rundeck/blob/master/spec/functions/validate_rd_policy/signature_spec.rb and https://github.com/puppet-community/puppet-rundeck/blob/master/spec/defines/config/resource_source_spec.rb

**Comment by jyaworski** [comment]
I'm holding on this until #134 gets merged.

**Comment by jyaworski** [comment]
Okay. This is good to be merged.

**Comment by nibalizer** [comment]
@jyaworski can you squash?

**Comment by jyaworski** [comment]
I rebased down into one commit; did you mean something else?

**Comment by nibalizer** [comment]
Thanks!

**Pull request merged**
